version: '3.8'

services:
  test-db:
    image: postgres:16
    container_name: test-db
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - '5433:5432'
