version: '3.8'

services:
  postgres:
    container_name: media-studio-db-dev
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PGUSER:-pg}
      POSTGRES_PASSWORD: ${PGPASSWORD:-pg}
      POSTGRES_DB: ${PGDATABASE:-media-studio-dev}
    healthcheck:
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
      test: ['CMD-SHELL', 'pg_isready -U ${PGUSER:-pg}']
    volumes:
      - media-studio_pg_data_dev:/var/lib/postgresql/data
    networks:
      - media-studio

  redis:
    container_name: media-studio-redis-dev
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - media-studio_redis_data_dev:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - media-studio

networks:
  media-studio:

volumes:
  media-studio_pg_data_dev:
    driver: local
  media-studio_redis_data_dev:
    driver: local
